name: first
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello aai"
      - name: multiline script
        run: |
          node -v
          npm -v
          python -v
      - name: python processor
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' 
        run: |
          import platform
          print(platform.processor())
        shell: python
