name: first
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello aai"      
      - name: echo a new string
        run: echo "hello Mac"
      - name: multiline script
        run: |
          node -v
          npm -v
          python -v
  run-wind-ps:
    runs-on: windows-latest
    steps:
      - name: list dir
        run: Get-Location
      - name: list dir bash
        run: pwd
        shell: bash 